# Movie Admin Service (stateless)
server:
  port: 9005

spring:
  application:
    name: admin-movies-service
  datasource:
    url: jdbc:sqlite:${DB_PATH:/data/nms-movies-ticketing.db}
# Uses in-memory data for business logic only

# Service discovery
eureka:
  client:
    service-url:
      defaultZone:  ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

# Health monitoring
management:
  endpoints:
    web:
      exposure:
        include: health

# where to store files (can be an absolute path, too)
app:
  upload:
    dir: ${APP_UPLOAD_DIR:uploads}

